/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2020-02-10 02:13:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/F:/wcEorI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wcExportAndImport/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/F:/wcEorI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wcExportAndImport/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1581249156883L));
    _jspx_dependants.put("jar:file:/F:/wcEorI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wcExportAndImport/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1511749306000L));
    _jspx_dependants.put("jar:file:/F:/wcEorI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wcExportAndImport/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511749306000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1581249383570L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();

	String name = "ssss";
	String username = "zzzz";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>个人中心</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./statics/img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./statics/bootstrap-3.3.7/dist/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./statics/layui/css/layui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./statics/css/navigation.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./statics/css/xoms.layout.css\" />\r\n");
      out.write("<link type=\"text/css\"  href=\"./statics/layui/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./statics/login/js/jquery-1.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"./statics/layui/layui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./statics/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./statics/layui/layui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./statics/bootstrap-3.3.7/dist/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../statics/img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../statics/bootstrap-3.3.7/dist/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../statics/layui/css/layui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../statics/css/navigation.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../statics/css/xoms.layout.css\" />\r\n");
      out.write("<link type=\"text/css\"  href=\"./statics/layui/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./statics/login/js/jquery-1.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"./statics/layui/layui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../statics/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../statics/layui/layui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../statics/bootstrap-3.3.7/dist/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 对话框css样式 -->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("html, body, div, img, span {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clearfix {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tzoom: 1;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".message {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-time {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 10px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-time-span {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 1px 10px;\r\n");
      out.write("\tbackground: #dcdcdc;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic-left {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 40px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-style {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-style-left {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pos, .pos-left {\r\n");
      out.write("\tmargin: 0 10px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pos:after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 14px;\r\n");
      out.write("\tleft: 100%;\r\n");
      out.write("\tborder-top: 5px solid transparent;\r\n");
      out.write("\tborder-left: 6px solid #b2e281;\r\n");
      out.write("\tborder-bottom: 5px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pos-left:before {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 14px;\r\n");
      out.write("\tright: 100%;\r\n");
      out.write("\tborder-top: 5px solid transparent;\r\n");
      out.write("\tborder-right: 6px solid #b2e281;\r\n");
      out.write("\tborder-bottom: 5px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bubble {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmax-width: 400px;\r\n");
      out.write("\tmin-height: 40px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\tbackground: #b2e281;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".plain {\r\n");
      out.write("\tpadding: 9px 13px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 导航栏 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 导航栏开始 -->\r\n");
      out.write("<nav class=\"navbar navbar-default container-fluid\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(path);
      out.write("/page/pageJump.do?path=views/index\">安布雷</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse \"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav \">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"");
      out.print(path);
      out.write("/page/pageJump.do?path=views/index\">个人中心</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown \"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">进口货物<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu active\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li><a href=\"");
      out.print(path);
      out.write("/my_orders/to_create.html\">到货计划表</a></li>-->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/page/pageJump.do?path=views/aArrivalPlan/aArrivalPlan\">到货计划表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown \"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">出口货物<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu active\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li><a href=\"");
      out.print(path);
      out.write("/my_orders/to_create.html\">出货计划表</a></li>-->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/page/pageJump.do?path=views/sShippingPlan/SShippingPlan\">出货计划表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">企业数据库<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/page/pageJump.do?path=views/product/productVO\">产品备案</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">企业信息<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li><a href=\"./company/companyUI\">企业基本信息</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/company/editCompany\">企业基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/customs/customsUI\">海关登记信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print(path);
      out.write("/customer/customerUI\">往来客户信息管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">您好！");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"http://localhost:8080/wcExportAndImport/page/login\">退出</a></li>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("<!-- 导航栏结束 -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t时间：2018-02-05\r\n");
      out.write("\t描述：网站主体开始\r\n");
      out.write("-->\r\n");
      out.write("\t<div class=\"col-lg-1 col-xs-12\"></div>\r\n");
      out.write("\t<div class=\"ztck-body col-lg-10 col-xs-12\">\r\n");
      out.write("\t\t<div class=\"container-fluid col-md-10 col-xs-12\">\r\n");
      out.write("\t\t\t<div style=\"width: 100px;\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left; width: 150px; height: 150px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(path);
      out.write("/statics/img/personal_photo.png\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"float: left; margin-left: 50px; margin-top: 20px;\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(name );
      out.write("</span><br /> <span>\r\n");
      out.write("\t\t\t\t\t余额:100000000000000000\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container col-md-3 col-xs-12\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--\r\n");
      out.write("    \t作者：offline\r\n");
      out.write("    \t时间：2018-02-05\r\n");
      out.write("    \t描述：标签页\r\n");
      out.write("    -->\r\n");
      out.write("\t\t<div class=\"container col-md-6 col-xs-12\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#stayReply\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\">问题订单</a></li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"#alreadyReply\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\">问题</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane active\" id=\"stayReply\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 700px; height: 250px; overflow-y: auto;\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane\" id=\"alreadyReply\">\r\n");
      out.write("\t\t\t\t\t<p>我是已回复的内容</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container col-md-6 col-xs-12\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#stayRead\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\">待办理事件</a></li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"#alreadyRead\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\">已完成事件</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane active\" id=\"stayRead\">\r\n");
      out.write("\t\t\t\t\t<!-- <p>年审</p> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane\" id=\"alreadyRead\">\r\n");
      out.write("\t\t\t\t\t<p>我是已经阅读了的内容</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container col-md-6 col-xs-12\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#Notice\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"tab\">公告</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane active\" id=\"Notice\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 600px; height: 250px; overflow-y: auto;\">公告</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"aa\" style=\"display: none;\">\r\n");
      out.write("\t\t<div id=\"container\" class=\"clearfix\"\r\n");
      out.write("\t\t\tstyle=\"width: 586px; height: 415px;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-left: 3px;\">\r\n");
      out.write("\t\t\t<textarea rows=\"4\" cols=\"82\" style=\"resize: none;\" id=\"content\"></textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("\t时间：2018-02-05\r\n");
      out.write("\t描述：主体结束\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("\t时间：2018-02-05\r\n");
      out.write("\t描述：网站尾部\r\n");
      out.write("-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("layui.use(['table','layer','form','laytpl'], function(){\r\n");
      out.write("\t  var table = layui.table,\r\n");
      out.write("\t  layer=layui.layer,\r\n");
      out.write("\t  form=layui.form,\r\n");
      out.write("\t  laytpl = layui.laytpl;\r\n");
      out.write("\t  $(\".feeda\").click(function(){\r\n");
      out.write("\t\t  $(\"#content\").val(\"\");\r\n");
      out.write("\t\t\tvar a=$(this).parent().find($(\"span\")).text();\r\n");
      out.write("\t\t\t//console.log(a)\r\n");
      out.write("\t\t\thui(a);\r\n");
      out.write("\t\t\t layer.open({\r\n");
      out.write("\t\t\t\t  type: 1 //Page层类型\r\n");
      out.write("\t\t\t\t  ,area: ['601px', '600px']\r\n");
      out.write("\t\t\t\t  ,title: '正在回复...'\r\n");
      out.write("\t\t\t\t  ,shade: 0 //遮罩透明度\r\n");
      out.write("\t\t\t\t  ,anim: 1 //0-6的动画形式，-1不开启\r\n");
      out.write("\t\t\t\t  ,content: $('#aa')\r\n");
      out.write("\t\t\t\t  ,btn: ['发送', '取消']\r\n");
      out.write("\t\t\t\t  ,yes:function(){\r\n");
      out.write("\t\t\t\t\t  var content=$(\"#content\").val();\r\n");
      out.write("\t\t\t\t\t \t $.ajax({\r\n");
      out.write("\t\t\t\t\t \t\turl:'");
      out.print(path);
      out.write("/feedback/QtReply.do',\r\n");
      out.write("\t\t\t\t\t \t\ttype:'POST',\r\n");
      out.write("\t\t\t\t\t \t\tdata:{\r\n");
      out.write("\t\t\t\t\t \t\t\tfeedbackid:a,\r\n");
      out.write("\t\t\t\t\t \t\t\tfeedback:content,\r\n");
      out.write("\t\t\t\t\t \t\t\t},\r\n");
      out.write("\t\t\t\t\t \t\tsuccess:function(msg){\r\n");
      out.write("\t\t\t\t\t \t\t\tif(msg.resultInfo.messageCode==888){\r\n");
      out.write("\t\t\t\t\t \t\t\t\tlayer.msg(\"回复成功\");\r\n");
      out.write("\t\t\t\t\t \t\t\t\t$(\"#content\").val(\"\");\r\n");
      out.write("\t\t\t\t\t \t\t\t    hui(a);\r\n");
      out.write("\t\t\t\t\t \t\t\t}else{\r\n");
      out.write("\t\t\t\t\t \t\t\t\tlayer.msg(\"回复失败\");\r\n");
      out.write("\t\t\t\t\t \t\t\t}\r\n");
      out.write("\t\t\t\t\t \t\t}\r\n");
      out.write("\t\t\t\t\t \t}); \r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t});  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t  $(function(){\r\n");
      out.write("\t\t\t console.log(\"%cZTCK\",\" text-shadow: 0 1px 0 #ccc,0 2px 0 #c9c9c9,0 3px 0 #bbb,0 4px 0 #b9b9b9,0 5px 0 #aaa,0 6px 1px rgba(0,0,0,.1),0 0 5px rgba(0,0,0,.1),0 1px 3px rgba(0,0,0,.3),0 3px 5px rgba(0,0,0,.2),0 5px 10px rgba(0,0,0,.25),0 10px 10px rgba(0,0,0,.2),0 20px 20px rgba(0,0,0,.15);font-size:5em\")\r\n");
      out.write("\t\t\t console.log(\"%c你打开控制台想看什么？\",\" text-shadow: 0 1px 0 #ccc,0 2px 0 #c9c9c9,0 3px 0 #bbb,0 4px 0 #b9b9b9,0 5px 0 #aaa,0 6px 1px rgba(0,0,0,.1),0 0 5px rgba(0,0,0,.1),0 1px 3px rgba(0,0,0,.3),0 3px 5px rgba(0,0,0,.2),0 5px 10px rgba(0,0,0,.25),0 10px 10px rgba(0,0,0,.2),0 20px 20px rgba(0,0,0,.15);font-size:5em\")\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t  });\r\n");
      out.write("\t  \r\n");
      out.write("\t//显示聊天记录\r\n");
      out.write("\t  function hui(b){\r\n");
      out.write("\t \t  $(\"#container\").empty();\r\n");
      out.write("\t \t\t$.ajax({\r\n");
      out.write("\t \t\t\turl:'");
      out.print(path);
      out.write("/feedback/hui.do',\r\n");
      out.write("\t \t\t\ttype:'post',\r\n");
      out.write("\t \t\t\tdata:{feedbackid:b},\r\n");
      out.write("\t \t\t\tsuccess:function(msg){\r\n");
      out.write("\t \t\t\t\t//console.log(msg);\r\n");
      out.write("\t \t\t\t\t//console.log(\"长度===\"+msg.length); \r\n");
      out.write("\t \t\t\t\tfor(var i=0;i<msg.length;i++){\r\n");
      out.write("\t \t\t\t\t\t  if(msg[i].identity==1){\r\n");
      out.write("\t \t\t\t\t\t\t $(\"#container\").append(\"<div class='message clearfix'> <p class='content-time'><span class='content-time-span'>\"+getDate(msg[i].messageSendingTime)+\"</span></p><img class='pic-left' src='");
      out.print(path );
      out.write("/images/kefutx.png'><div class='text-style-left'><div class='pos-left'><div class='bubble'><div class='plain'>\"+msg[i].feedback+\"</div></div></div></div></div>\"); \r\n");
      out.write("\t \t\t\t\t\t\t } else{\r\n");
      out.write("\t \t\t\t\t\t\t\t$(\"#container\").append(\"<div class='message clearfix'> <p class='content-time'><span class='content-time-span'>\"+getDate(msg[i].messageSendingTime)+\"</span></p><img class='pic' src='");
      out.print(path );
      out.write("/images/kehutx.png'><div class='text-style'><div class='pos'><div class='bubble'><div class='plain'>\"+msg[i].feedback+\"</div></div></div></div></div>\"); \r\n");
      out.write("\t \t\t\t\t\t\t }\r\n");
      out.write("\t \t\t\t\t/* \tconsole.log(\"i===\"+i);\r\n");
      out.write("\t \t\t\t\t\tconsole.log(\"id==\"+msg[i].userid); */\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t\tvar div = document.getElementById('container');\r\n");
      out.write("\t\t\t  \t\tdiv.scrollTop = div.scrollHeight;\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t  function getDate(tm){ \r\n");
      out.write("\t\t    var tt=new Date(tm).toLocaleString(); \r\n");
      out.write("\t\t    return tt; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t//年审时间提示\r\n");
      out.write("\t  var annualTime = $(\"#stayRead\")\r\n");
      out.write("\t  $(function(){\r\n");
      out.write("\t  \t$.ajax({\r\n");
      out.write("\t  \t\ttype:\"get\",\r\n");
      out.write("\t  \t\tasync:false,\r\n");
      out.write("\t  \t\tdataType: \"json\",\r\n");
      out.write("\t  \t\turl:\"");
      out.print(path);
      out.write("/company/AnnualInspection.do\",\r\n");
      out.write("\t  \t\t//data:userID,\r\n");
      out.write("\t  \t\tsuccess:function(data){\r\n");
      out.write("\t  \t\t\tconsole.log(data)\r\n");
      out.write("\t  \t\t\tif(data.status == 400){\r\n");
      out.write("\t  \t\t\t\t//layer.alert(data.msg)\r\n");
      out.write("\t  \t\t\t\tvar p = $(['<p>'+data.msg+'</p>'].join(''));\r\n");
      out.write("\t  \t\t\t\tannualTime.append(p);\r\n");
      out.write("\t  \t\t\t}else{\r\n");
      out.write("\t  \t\t\t\tlayer.alert(data.msg);\r\n");
      out.write("\t  \t\t\t}\r\n");
      out.write("\t  \t\t\t\t},\r\n");
      out.write("\t  \t\terror:function(){\r\n");
      out.write("\t  \t\t\talert(\"年审接口出错了\")\r\n");
      out.write("\t  \t\t}\r\n");
      out.write("\t  \t\t});\r\n");
      out.write("\t  \t\t})\t  \r\n");
      out.write("\t  \r\n");
      out.write("});\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(273,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("feedbacks");
      // /WEB-INF/views/index.jsp(273,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feedbacks}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a class=\"btn feeda\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feedbacks.feedbackid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">订单号：");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feedbacks.orderNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",问题类型:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feedbacks.problemType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",详细内容：");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(feedbacks.feedback,0, 15)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("...</a><br>\r\n");
            out.write("\t\t\t\t\t\t\t\t<span style=\"display: none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${feedbacks.feedbackid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
