/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2020-02-15 05:20:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.after.customsDeclaration;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class exportUploadFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/wcEorI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wcExportAndImport/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1581249383570L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/statics/transfer/layui/css/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/transfer/layui/layui.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/transfer/layui/layui.all.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/js/common/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"layui-form-item\">\r\n");
      out.write("    <label class=\"layui-form-label sendOrder-left-paading\"></label>\r\n");
      out.write("    <input type=\"hidden\" id=\"filePath\" name=\"filePath\" />\r\n");
      out.write("    <div class=\"layui-input-inline\" style=\"display: inline-block;position: relative;float: left;margin-right: 10px;width:80%;\">\r\n");
      out.write("        <div class=\"layui-upload\">\r\n");
      out.write("            <button type=\"button\" class=\"layui-btn\" id=\"testList\">选择文件</button>\r\n");
      out.write("            <div class=\"layui-upload-list\">\r\n");
      out.write("                <table class=\"layui-table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr><th>文件名</th>\r\n");
      out.write("                        <th>大小</th>\r\n");
      out.write("                        <th>状态</th>\r\n");
      out.write("                        <th>操作</th>\r\n");
      out.write("                    </tr></thead>\r\n");
      out.write("                    <tbody id=\"demoList\"></tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"layui-btn layui-btn-disabled\" id=\"testListAction\">开始上传</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"");
      out.print(path);
      out.write("/AArrivalPlan/downloadFile.do\" method=\"get\" id=\"btnform\" class=\"layui-form enditform\" >\r\n");
      out.write("        <input name=\"id\" type=\"hidden\" id =\"fileAdress\">\r\n");
      out.write("        \r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"");
      out.print(path);
      out.write("/contract/exportShippingPlanInvoice.do\" method=\"get\" id=\"btnformInvoice\" class=\"layui-form enditform\" >\r\n");
      out.write("        <input name=\"id\" type=\"hidden\" id =\"fileAdressInvoice\">\r\n");
      out.write("        \r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"");
      out.print(path);
      out.write("/contract/exportShippingPlanPackList.do\" method=\"get\" id=\"btnformPacking\" class=\"layui-form enditform\" >\r\n");
      out.write("        <input name=\"id\" type=\"hidden\" id =\"fileAdressPacking\">\r\n");
      out.write("        \r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"");
      out.print(path);
      out.write("/contract/exportShippingContract.do\" method=\"get\" id=\"btnformContract\" class=\"layui-form enditform\" >\r\n");
      out.write("        <input name=\"id\" type=\"hidden\" id =\"fileAdressContract\">\r\n");
      out.write("        \r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var id = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("var demoListView = $('#demoList')\r\n");
      out.write("var invoice = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.invoice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("//删除回显文件的id\r\n");
      out.write("var fileId;\r\n");
      out.write("// 默认发票，装箱单，合同三个文件回显\r\n");
      out.write("$(function(){\r\n");
      out.write("            var tr = $(['<tr id=\"upload+\">'\r\n");
      out.write("                        , '<td style = \"width:200px;\">发票.xlxs</td>'\r\n");
      out.write("                        , '<td>50kb</td>'\r\n");
      out.write("                        , '<td style=\"color: #5FB878;\">已上传</td>'\r\n");
      out.write("                        , '<td>'\r\n");
      out.write("                        , '<button class=\"layui-btn layui-btn-xs layui-btn-downLoad demo-downLoad\" onclick = \"downLoadInvoice('+id+')\">下载</button>'\r\n");
      out.write("                        , '</td>'\r\n");
      out.write("                        , '</tr>'\r\n");
      out.write("                        ,'<tr id=\"upload+\">'\r\n");
      out.write("                        , '<td style = \"width:200px;\">装箱单.xlxs</td>'\r\n");
      out.write("                        , '<td>50kb</td>'\r\n");
      out.write("                        , '<td style=\"color: #5FB878;\">已上传</td>'\r\n");
      out.write("                        , '<td>'\r\n");
      out.write("                        , '<button class=\"layui-btn layui-btn-xs layui-btn-downLoad demo-downLoad\" onclick = \"downLoadPacking('+id+')\">下载</button>'\r\n");
      out.write("                        , '</td>'\r\n");
      out.write("                        , '</tr>'\r\n");
      out.write("                        ,'<tr id=\"upload+\">'\r\n");
      out.write("                        , '<td style = \"width:200px;\">合同.xlxs</td>'\r\n");
      out.write("                        , '<td>50kb</td>'\r\n");
      out.write("                        , '<td style=\"color: #5FB878;\">已上传</td>'\r\n");
      out.write("                        , '<td>'\r\n");
      out.write("                        , '<button class=\"layui-btn layui-btn-xs layui-btn-downLoad demo-downLoad\" onclick = \"downLoadContract('+id+')\">下载</button>'\r\n");
      out.write("                        , '</td>'\r\n");
      out.write("                        , '</tr>'].join(''));\r\n");
      out.write("            demoListView.append(tr);\r\n");
      out.write("})\r\n");
      out.write("//已上传文件回显\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"get\",\r\n");
      out.write("        url: \"");
      out.print(path);
      out.write("/AArrivalPlan/findPicture.do\",\r\n");
      out.write("        data:{'invoice':invoice},\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        success: function(data){\r\n");
      out.write("            for(var i = 0;i<data.length;i++){\r\n");
      out.write("            var id = data[i].id \r\n");
      out.write("            fileId = id;\r\n");
      out.write("            var tr = $(['<tr id=\"upload\">'\r\n");
      out.write("                        , '<td style = \"width:200px;\">' + data[i].fileName + '</td>'\r\n");
      out.write("                        , '<td>' + data[i].size + 'kb</td>'\r\n");
      out.write("                        , '<td style=\"color: #5FB878;\">已上传</td>'\r\n");
      out.write("                        , '<td>'\r\n");
      out.write("                        , '<button class=\"layui-btn layui-btn-xs layui-btn-danger demo-delete\" onclick = \"fileDel()\">删除</button>'\r\n");
      out.write("                        , '<button class=\"layui-btn layui-btn-xs layui-btn-afterDownLoad demo-downLoad\" onclick = \"downLoad('+id+')\">下载</button>'\r\n");
      out.write("                        , '</td>'\r\n");
      out.write("                        , '</tr>'].join(''));\r\n");
      out.write("            demoListView.append(tr);\r\n");
      out.write("        }\r\n");
      out.write("\t}\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("//回显删除功能\r\n");
      out.write("function fileDel(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("        url: \"");
      out.print(path);
      out.write("/AArrivalPlan/deleteFileByID.do\",\r\n");
      out.write("        data:{'id':fileId},\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        success: function(data){\r\n");
      out.write("        \t if (data.status == 200) {\r\n");
      out.write("             \tlayer.msg(data.msg, {\r\n");
      out.write("             \t\ticon: 1,\r\n");
      out.write("             \t\ttime: 700,\r\n");
      out.write("             \t},function(){\r\n");
      out.write("         \t\t\t\tlocation.reload();\r\n");
      out.write("             \t\t});\r\n");
      out.write("             }else{\r\n");
      out.write("            \tlayer.msg(data.msg,{\r\n");
      out.write("            \t\ticon: 2,\r\n");
      out.write("            \t\ttime: 700,\r\n");
      out.write("            \t},function(){\r\n");
      out.write("        \t\t\t\tlocation.reload();\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            }\r\n");
      out.write("\t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//回显下载文件\r\n");
      out.write("function downLoad(id){\r\n");
      out.write("\t$(\"#fileAdress\").val(id)\r\n");
      out.write("\t$('#btnform').submit();\r\n");
      out.write("}\r\n");
      out.write("//回显下载发票文件\r\n");
      out.write("function downLoadInvoice(id){\r\n");
      out.write("\t$(\"#fileAdressInvoice\").val(id)\r\n");
      out.write("\t$('#btnformInvoice').submit();\r\n");
      out.write("}\r\n");
      out.write("//回显下载装箱单文件\r\n");
      out.write("function downLoadPacking(id){\r\n");
      out.write("\t$(\"#fileAdressPacking\").val(id)\r\n");
      out.write("\t$('#btnformPacking').submit();\r\n");
      out.write("}\r\n");
      out.write("//回显下载合同文件\r\n");
      out.write("function downLoadContract(id){\r\n");
      out.write("\t$(\"#fileAdressContract\").val(id)\r\n");
      out.write("\t$('#btnformContract').submit();\r\n");
      out.write("}\r\n");
      out.write("layui.use(['upload'], function(){\r\n");
      out.write("\tvar $ = layui.jquery,\r\n");
      out.write("\t   upload = layui.upload;\r\n");
      out.write("//多文件列表\r\n");
      out.write("var uploadListIns = upload.render({\r\n");
      out.write("    elem: '#testList'\r\n");
      out.write("    , url: '");
      out.print(path);
      out.write("/AArrivalPlan/uploadFile.do'\r\n");
      out.write("    //设置图片上传的大小\r\n");
      out.write("    , size: 31457280\r\n");
      out.write("    //设置图片上传的格式\r\n");
      out.write("    //, acceptMime: 'image/jpg, image/png'\r\n");
      out.write("    , accept:'file'\r\n");
      out.write("    , multiple: true\r\n");
      out.write("    //参数名\r\n");
      out.write("    , field:'files'\r\n");
      out.write("    //禁用自动上传\r\n");
      out.write("    , auto: false\r\n");
      out.write("    //上传按钮\r\n");
      out.write("    , bindAction: '#testListAction'\r\n");
      out.write("    //请求前的操作\r\n");
      out.write("    , before: function () {\r\n");
      out.write("        //添加参数\r\n");
      out.write("        var data = {}\r\n");
      out.write("        data.invoice = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.invoice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("        this.data = data;\r\n");
      out.write("    }\r\n");
      out.write("    //每一次请求结束后操作\r\n");
      out.write("    , choose: function (obj) {\r\n");
      out.write("        var files = this.files = obj.pushFile(); //将每次选择的文件追加到文件队列\r\n");
      out.write("        //读取本地文件\r\n");
      out.write("        obj.preview(function (index, file, result) {\r\n");
      out.write("        \tconsole.log(index)\r\n");
      out.write("        \t//console.log(file)\r\n");
      out.write("        \t//console.log(result)\r\n");
      out.write("        \t\r\n");
      out.write("            if($(\"#testListAction\").hasClass(\"layui-btn-disabled\")){\r\n");
      out.write("            \t$(\"#testListAction\").removeClass(\"layui-btn-disabled\");\r\n");
      out.write("            }\r\n");
      out.write("            var tr = $(['<tr id=\"upload-' + index + '\">'\r\n");
      out.write("                , '<td style = \"width:200px;\">' + file.name + '</td>'\r\n");
      out.write("                , '<td>' + (file.size / 1014).toFixed(1) + 'kb</td>'\r\n");
      out.write("                , '<td>等待上传</td>'\r\n");
      out.write("                , '<td>'\r\n");
      out.write("                , '<button class=\"layui-btn layui-btn-xs layui-btn-danger demo-delete\">删除</button>'\r\n");
      out.write("                , '</td>'\r\n");
      out.write("                , '</tr>'].join(''));\r\n");
      out.write("            //单个重传  ,'<button class=\"layui-btn layui-btn-xs demo-reload layui-hide\">重传</button>'\r\n");
      out.write("            /*tr.find('.demo-reload').on('click', function(){\r\n");
      out.write("                obj.upload(index, file);\r\n");
      out.write("            });*/\r\n");
      out.write("            //删除\r\n");
      out.write("            tr.find('.demo-delete').on('click', function () {\r\n");
      out.write("                delete file[index]; //删除对应的文件\r\n");
      out.write("                tr.remove();\r\n");
      out.write("                uploadListIns.config.elem.next()[0].value = ''; //清空 input file 值，以免删除后出现同名文件不可选\r\n");
      out.write("            });\r\n");
      out.write("            demoListView.append(tr);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    , done: function (res, index, upload) {\r\n");
      out.write("        if (res.status == 200) { //上传成功\r\n");
      out.write("        \t var tr = demoListView.find('tr#upload-' + index), tds = tr.children();\r\n");
      out.write("             tds.eq(2).html('<span style=\"color: #5FB878;\">上传成功</span>');\r\n");
      out.write("             location.reload();\r\n");
      out.write("            //tds.eq(3).html(''); //清空操作\r\n");
      out.write("            //$(\"#demoList\").html('');\r\n");
      out.write("            //return delete this.files[index]; //删除文件队列已经上传成功的文件\r\n");
      out.write("            //this.error(index, upload);\r\n");
      out.write("\t        }\r\n");
      out.write("    \t}\r\n");
      out.write("    , error: function (res,index, upload) {\r\n");
      out.write("        var tr = demoListView.find('tr#upload-' + index)\r\n");
      out.write("            , tds = tr.children();\r\n");
      out.write("        tds.eq(2).html('<span style=\"color: #FF5722;\">上传失败</span>');\r\n");
      out.write("        tds.eq(3).find('.demo-reload').removeClass('layui-hide'); //显示重传\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("/* function noFile() {\r\n");
      out.write("\tvar content = $(\"#demoList\").html();\r\n");
      out.write("\tif (content== null || content == 0) {\r\n");
      out.write("\t    layer.alert(\"请选择文件\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} */\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
