/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2020-02-15 05:19:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.after.customsDeclaration;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exportReceivables_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>收款页面</title>\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/statics/layui/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/statics/css/user/user.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/layui/layui.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/statics/js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/* ul li 仿select下拉框样式美化 */\r\n");
      out.write("\r\n");
      out.write(" li {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("/* #select {\r\n");
      out.write("    border: 1px solid #9D9D9D;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    margin:5px 0 0 10px;\r\n");
      out.write("    padding: 5px 5px 0 0;\r\n");
      out.write("} */\r\n");
      out.write(".select-head {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    line-height: 24px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".select-head .select-head-cont {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".select-head .select-icon {\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write(".option {\r\n");
      out.write("    margin: 50px 0 0 60px;\r\n");
      out.write("    width: 176px;\r\n");
      out.write("    height:200px;\r\n");
      out.write("    color: black;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: 1px #9D9D9D solid;\r\n");
      out.write("    display: none;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    top: 23px;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    overflow-y:auto;\r\n");
      out.write("}\r\n");
      out.write(".option .option-item {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    line-height: 24px;\r\n");
      out.write("    padding: 10px 5px 0 12px;\r\n");
      out.write("}\r\n");
      out.write(".option-item:hover {\r\n");
      out.write("    background: #009688 !important;\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("    <form action=\"\" method=\"post\" id=\"enditform\" class=\"layui-form enditform\">\r\n");
      out.write("    \t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">仓储费</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"cangchufeiInput\"  value=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"cangchufeiSelect\" class =\"layui-select\" lay-filter=\"cangchufeiSelect\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">报关费</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"baoguanfeiInput\" value=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"baoguanfeiSelect\" class =\"layui-select\" lay-filter=\"baoguanfeiSelect\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">商检费</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"shangjianfeiInput\" value=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"shangjianfeiSelect\" class =\"layui-select\" lay-filter=\"shangjianfeiSelect\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">转关费</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"zhuanguanfeiInput\"  value=\"\">\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"zhuanguanfeiSelect\" class =\"layui-select\" lay-filter=\"zhuanguanfeiSelect\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">其他1</label> \r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"other1Input\"  value=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"other1Select\" class =\"layui-select\" lay-filter=\"other1Select\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">其他2</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<input type=\"text\"  class=\"layui-input\" name=\"passWord\" id=\"other2Input\"  value=\"\">\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t<select name=\"paiDan\" id=\"other2Select\" class =\"layui-select\" lay-filter=\"other2Select\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t<option>请选择单位</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">备注</label> \r\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\r\n");
      out.write("\t\t\t <input type=\"text\"  class=\"layui-input\" lay-verify=\"required\" name=\"passWord\" id=\"passWord\"  value=\"\" style=\"width:90%;\" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t <label class=\"layui-form-label\">计算公式</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\" id = \"gongshibianliang\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t<label class=\"layui-form-label\">总金额</label>\r\n");
      out.write("\t\t\t<div class=\"layui-inline\" id =\"jinebianliang\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar cangchufeiInput = 0;\r\n");
      out.write("\tvar cangchufeiSelect = 0;\r\n");
      out.write("\tvar baoguanfeiInput = 0;\r\n");
      out.write("\tvar baoguanfeiSelect = 0;\r\n");
      out.write("\tvar shangjianfeiInput = 0;\r\n");
      out.write("\tvar shangjianfeiSelect = 0;\r\n");
      out.write("\tvar zhuanguanfeiInput = 0;\r\n");
      out.write("\tvar zhuanguanfeiSelect = 0;\r\n");
      out.write("\tvar other1Input = 0;\r\n");
      out.write("\tvar other1Select = 0;\r\n");
      out.write("\tvar other2Input = 0;\r\n");
      out.write("\tvar other2Select = 0;\r\n");
      out.write("\tvar jisuangongshi = \" \";\r\n");
      out.write("\tvar zongjine = 0;\r\n");
      out.write("\tlayui.use(['form', 'jquery'],function(){\r\n");
      out.write("\t    var form = layui.form;\r\n");
      out.write("\t    var $ = layui.jquery;\r\n");
      out.write("\t\t//仓储费\r\n");
      out.write("\t\t$(\"#cangchufeiInput\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"仓储费\") != -1){//如果计算公式不为空，并且包含仓储费，那么就需要删除之前的仓储费，并重新添加新修改的仓储费用\r\n");
      out.write("\t\t\t\tzongjine = zongjine - cangchufeiInput * cangchufeiSelect//总金额中已经包含上次输入的仓储费了，需要删除之前添加的仓储费\r\n");
      out.write("\t\t\t\tcangchufeiInput = 0//仓储费置空\r\n");
      out.write("\t\t\t\tcangchufeiInput = $(\"#cangchufeiInput\").val()//仓储费获取赋值\r\n");
      out.write("\t\t\t\t//重置总金额\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(cangchufeiInput != 0){//仓储费改为新的仓储费\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + cangchufeiInput * cangchufeiSelect//增加新的仓储费用\r\n");
      out.write("\t\t\t\t\t//重置总金额\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{//如果计算公式不为空，并且计算公式没有包含仓储费，或计算公式为空，就继续执行\r\n");
      out.write("\t\t\t\tcangchufeiInput = $(\"#cangchufeiInput\").val()//仓储费获取赋值\r\n");
      out.write("\t\t\t\tif(cangchufeiInput != 0 && cangchufeiSelect != 0){//判断仓储费是否有值，仓储单位是否为数值，如果没有值且不为数值，那么就直接结束\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){//正常情况，仓储费和单位都有值，并且是用户第一次输入，计算公式为空\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"仓储费*单位\" //新增计算公式，并且为第一位置\r\n");
      out.write("\t\t\t\t\t\tzongjine = cangchufeiInput * cangchufeiSelect //总金额第一次计算\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{//正常情况，仓储费和单位都有值，并且计算公式有值，不是用户最先输入的仓储费\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+仓储费*单位\" //在计算公式已经存在数据的情况下，继续添加需要的公式\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + cangchufeiInput * cangchufeiSelect//增加仓储费用\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t//仓储费用正常添加的情况下，要执行页面展示 的 计算公式的重置操作 和 总金额的重置操作\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t//仓储单位\r\n");
      out.write("\t\t//监听layui select下拉框的值\r\n");
      out.write("\t\tform.on('select(cangchufeiSelect)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"仓储费\") != -1){//如果计算公式不为空，并且包含仓储费，那么就需要删除之前的仓储费，并重新添加新修改的仓储费用\r\n");
      out.write("\t\t\t\tzongjine = zongjine - cangchufeiInput * cangchufeiSelect//总金额中已经包含上次输入的仓储费了，需要删除之前添加的仓储费\r\n");
      out.write("\t\t\t\tcangchufeiSelect = 0//仓储单位置空\r\n");
      out.write("\t\t\t\tcangchufeiSelect = data.value;//仓储单位获取赋值\r\n");
      out.write("\t\t\t\tif(cangchufeiSelect == \"请选择单位\"){//防止仓储单位赋值为字符串而引起总金额值错误\r\n");
      out.write("\t\t\t\t\tcangchufeiSelect = 0 //当仓储单位为请选择单位时，赋值为0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//重置总金额\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(cangchufeiSelect != 0){//仓储单位有值，并且是新的修改的数值，则，继续增加新的仓储费用\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + cangchufeiInput * cangchufeiSelect//增加新的仓储费用\r\n");
      out.write("\t\t\t\t\t//重置总金额\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t//如果计算公式不为空，并且计算公式没有包含仓储费，或计算公式为空，就继续执行\r\n");
      out.write("\t\t\t\tcangchufeiSelect = data.value;//仓储单位获取赋值\r\n");
      out.write("\t\t\t\tif(cangchufeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tcangchufeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(cangchufeiInput != 0 && cangchufeiSelect != 0){//判断仓储费是否有值，仓储单位是否为数值，如果没有值且不为数值，那么就直接结束\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){//正常情况，仓储费和单位都有值，并且是用户第一次输入，计算公式为空\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"仓储费*单位\" //新增计算公式，并且为第一位置\r\n");
      out.write("\t\t\t\t\t\tzongjine = cangchufeiInput * cangchufeiSelect //总金额第一次计算\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{//正常情况，仓储费和单位都有值，并且计算公式有值，不是用户最先输入的仓储费\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+仓储费*单位\" //在计算公式已经存在数据的情况下，继续添加需要的公式\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + cangchufeiInput * cangchufeiSelect//增加仓储费用\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t//仓储费用正常添加的情况下，要执行页面展示 的 计算公式的重置操作 和 总金额的重置操作\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');//select是固定写法 不是选择器\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//此处使用change方法监听无效\r\n");
      out.write("\t\t/* $(\"#cangchufeiSelect\").change(function(){\r\n");
      out.write("\t\t$(\"#cangchufeiSelect\").bind(\"select propertychange\",function(){\r\n");
      out.write("\t\t\tcangchufeiSelect = $(this).children('option:selected').val()\t\r\n");
      out.write("\t\t\tconsole.log(cangchufeiSelect)\r\n");
      out.write("\t\t}) */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//报关费\r\n");
      out.write("\t\t$(\"#baoguanfeiInput\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"报关费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\tbaoguanfeiInput = 0\r\n");
      out.write("\t\t\t\tbaoguanfeiInput = $(\"#baoguanfeiInput\").val()\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(baoguanfeiInput != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tbaoguanfeiInput = $(\"#baoguanfeiInput\").val()\r\n");
      out.write("\t\t\t\tif(baoguanfeiInput != 0 && baoguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"报关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+报关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//报关单位\r\n");
      out.write("\t\tform.on('select(baoguanfeiSelect)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"报关费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\tbaoguanfeiSelect = 0\r\n");
      out.write("\t\t\t\tbaoguanfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(baoguanfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tbaoguanfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(baoguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tbaoguanfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(baoguanfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tbaoguanfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(baoguanfeiInput != 0 && baoguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"报关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+报关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + baoguanfeiInput * baoguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//商检费\r\n");
      out.write("\t\t$(\"#shangjianfeiInput\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"商检费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\tshangjianfeiInput = 0\r\n");
      out.write("\t\t\t\tshangjianfeiInput = $(\"#shangjianfeiInput\").val()\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(shangjianfeiInput != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshangjianfeiInput = $(\"#shangjianfeiInput\").val()\r\n");
      out.write("\t\t\t\tif(shangjianfeiInput != 0 && shangjianfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"商检费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+商检费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//商检单位\r\n");
      out.write("\t\tform.on('select(shangjianfeiSelect)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"商检费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\tshangjianfeiSelect = 0\r\n");
      out.write("\t\t\t\tshangjianfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(shangjianfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tshangjianfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(shangjianfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tshangjianfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(shangjianfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tshangjianfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(shangjianfeiInput != 0 && shangjianfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"商检费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+商检费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + shangjianfeiInput * shangjianfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//转关费\r\n");
      out.write("\t\t$(\"#zhuanguanfeiInput\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"转关费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\tzhuanguanfeiInput = 0\r\n");
      out.write("\t\t\t\tzhuanguanfeiInput = $(\"#zhuanguanfeiInput\").val()\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiInput != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tzhuanguanfeiInput = $(\"#zhuanguanfeiInput\").val()\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiInput != 0 && zhuanguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"转关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+转关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//转关单位\r\n");
      out.write("\t\tform.on('select(zhuanguanfeiSelect)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"转关费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\tzhuanguanfeiSelect = 0\r\n");
      out.write("\t\t\t\tzhuanguanfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tzhuanguanfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tzhuanguanfeiSelect = data.value;\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiSelect == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tzhuanguanfeiSelect = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(zhuanguanfeiInput != 0 && zhuanguanfeiSelect != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"转关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+转关费*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + zhuanguanfeiInput * zhuanguanfeiSelect\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//其他1费用\r\n");
      out.write("\t\t$(\"#other1Input\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"其他1费用\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - other1Input * other1Select\r\n");
      out.write("\t\t\t\tother1Input = 0\r\n");
      out.write("\t\t\t\tother1Input = $(\"#other1Input\").val()\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(other1Input != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tother1Input = $(\"#other1Input\").val()\r\n");
      out.write("\t\t\t\tif(other1Input != 0 && other1Select != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"其他1费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+其他1费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//其他1单位\r\n");
      out.write("\t\tform.on('select(other1Select)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"其他1费用\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - other1Input * other1Select\r\n");
      out.write("\t\t\t\tother1Select = 0\r\n");
      out.write("\t\t\t\tother1Select = data.value;\r\n");
      out.write("\t\t\t\tif(other1Select == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tother1Select = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(other1Select != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tother1Select = data.value;\r\n");
      out.write("\t\t\t\tif(other1Select == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tother1Select = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(other1Input != 0 && other1Select != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"其他1费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+其他1费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + other1Input * other1Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t//其他2费用\r\n");
      out.write("\t\t$(\"#other2Input\").bind(\"input propertychange\",function(event){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"其他2费用\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - other2Input * other2Select\r\n");
      out.write("\t\t\t\tother2Input = 0\r\n");
      out.write("\t\t\t\tother2Input = $(\"#other2Input\").val()\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(other2Input != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tother2Input = $(\"#other2Input\").val()\r\n");
      out.write("\t\t\t\tif(other2Input != 0 && other2Select != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"其他2费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+其他2费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//其他2单位\r\n");
      out.write("\t\tform.on('select(other2Select)', function(data){\r\n");
      out.write("\t\t\tif(jisuangongshi != \" \" && jisuangongshi.indexOf(\"其他2费用费\") != -1){\r\n");
      out.write("\t\t\t\tzongjine = zongjine - other2Input * other2Select\r\n");
      out.write("\t\t\t\tother2Select = 0\r\n");
      out.write("\t\t\t\tother2Select = data.value;\r\n");
      out.write("\t\t\t\tif(other2Select == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tother2Select = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\tif(other2Select != 0){\r\n");
      out.write("\t\t\t\t\tzongjine = zongjine + other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tother2Select = data.value;\r\n");
      out.write("\t\t\t\tif(other2Select == \"请选择单位\"){\r\n");
      out.write("\t\t\t\t\tother2Select = 0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(other2Input != 0 && other2Select != 0){\r\n");
      out.write("\t\t\t\t\tif(jisuangongshi == \" \"){\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"其他2费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tjisuangongshi = jisuangongshi + \"+其他2费用*单位\"\r\n");
      out.write("\t\t\t\t\t\tzongjine = zongjine + other2Input * other2Select\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").html(\" \")\r\n");
      out.write("\t\t\t\t\t$(\"#gongshibianliang\").append(\"<div>\"+jisuangongshi+\"</div>\");\r\n");
      out.write("\t\t\t\t\t$(\"#jinebianliang\").append(\"<div>\"+zongjine+\"</div>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tform.render('select');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var paiDanOption = \"<option value= ''></option>\\n\";\r\n");
      out.write("var resultData;\r\n");
      out.write("var obj = new Object();\r\n");
      out.write(" $.ajax({\r\n");
      out.write("\tasync:false,\r\n");
      out.write("\turl:'");
      out.print(path);
      out.write("/customsDeclaration/getUser.do',\r\n");
      out.write("\ttype:'get',\r\n");
      out.write("\tsuccess:function(data){\r\n");
      out.write("\t\tresultData = data;\r\n");
      out.write("\t\t//console.log(resultData)\r\n");
      out.write("\t\tfor(var i = 0 ; i < resultData.length ; i++){\r\n");
      out.write("\t\t\tvar id = resultData[i].id\r\n");
      out.write("\t\t\tvar userName = resultData[i].userName;\r\n");
      out.write("\t\t\tobj[userName] = id\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t//console.log(obj)\r\n");
      out.write("\t\t/* for(var x in resultData){\r\n");
      out.write("\t\t\tpaiDanOption +='<option value = \"'+resultData[x].userName+'\">'+resultData[x].userName+'</option>\\n';\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t//for (var k=0;k<resultData.length; k++) {\r\n");
      out.write("\t        $(\"#cangchufeiSelect\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#cangchufeiSelect\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#cangchufeiSelect\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t        \r\n");
      out.write("\t        $(\"#baoguanfeiSelect\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#baoguanfeiSelect\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#baoguanfeiSelect\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t        \r\n");
      out.write("\t        $(\"#shangjianfeiSelect\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#shangjianfeiSelect\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#shangjianfeiSelect\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t        \r\n");
      out.write("\t        $(\"#zhuanguanfeiSelect\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#zhuanguanfeiSelect\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#zhuanguanfeiSelect\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t        \r\n");
      out.write("\t        $(\"#other1Select\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#other1Select\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#other1Select\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t        \r\n");
      out.write("\t        $(\"#other2Select\").append(\"<option value='1'>1</option>\");\r\n");
      out.write("\t        $(\"#other2Select\").append(\"<option value='2'>2</option>\");\r\n");
      out.write("\t        $(\"#other2Select\").append(\"<option value='3'>3</option>\");\r\n");
      out.write("\t    //}\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
